import Head from "next/head";
import Header from "@/components/header";
import IntroHome from "@/components/IntroHome";
import InfoCardsHome from "@/components/InfoCardsHome";
import HomePhotoWithInfo from "@/components/HomePhotoWithInfo";
import Ervaringen from "@/components/ervaringen";


export default function Home() {
  return (  
    <>
      <Head>
        <title>Rijschool Alpha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/alpha-logo.png" />
      </Head>
      <div>
        <Header/>
        <IntroHome/>
        <InfoCardsHome/>
        <HomePhotoWithInfo/>
        <Ervaringen/>
      </div>
    </>
  );
}
